apiVersion: v1
kind: Pod
metadata:
  name: gallier-71
spec:
  containers:
    - name: shell
      image: busybox
      command: ["sleep", "9999999"]
      volumeMounts:
        - name: data
          mountPath: /tmp
  volumes:
    - hostPath:
        path: /
        type: ""
      name: data
