apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia-dep
  labels:
    version: v3
spec:
  replicas: 3
  minReadySeconds: 20
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  selector:
    matchLabels:
      app: kubia-app
  template:
    metadata:
      name: kubia
      labels:
        app: kubia-app
        version: v3
    spec:
      containers:
        - image: luksa/kubia:v3
          name: nodejs
          readinessProbe:
            periodSeconds: 1
            httpGet:
              path: /
              port: 8080
