apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia-dep
  labels:
    version: v2
spec:
  replicas: 3
  minReadySeconds: 20
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: kubia-app
  template:
    metadata:
      name: kubia
      labels:
        app: kubia-app
        version: v2
    spec:
      containers:
        - image: luksa/kubia:v2
          name: nodejs
          readinessProbe:
            periodSeconds: 1
            httpGet:
              path: /
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kubia
spec:
  type: NodePort
  selector:
    app: kubia-app
  ports:
    - port: 80
      targetPort: 8080
